package com.example.Student_Library_Management_System.Services;

import com.example.Student_Library_Management_System.Enums.CardStatus;
import com.example.Student_Library_Management_System.Models.Card;
import com.example.Student_Library_Management_System.Models.Student;
import com.example.Student_Library_Management_System.Repositories.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class StudentService {
    @Autowired
    StudentRepository studentRepository;

    public String createStudent(Student student){

        //Student from the postman is already the basic attributes set.

        //Card Should be autogenerated when createStudent function is called.
        Card card = new Card(); // to create card
        card.setCardStatus(CardStatus.ACTIVATED);
        card.setStudent(student); // connect card and student entity
        //Foreign key attribute
        //IMPORTANT
        // --> it will give you foreign key value of student entity to operate in child table corresponding to its value

        //Let's go to the student
        student.setCard(card); // saving card for this student --> bidirectional final step

        //If there was a unidirectional mapping : we had to save both of them
        //studentRepo.save () and cardRepo.save()
        //But we are super advance and are using bidirectional : Child will automatically be saved.
        //By cascading effect, child will automatically be saved (cardRepo will be saved)
        studentRepository.save(student);

        return "student & card added successfully";
    }

    public String getNameByEmail(String email){
        Student student = studentRepository.findByEmail(email);
        return student.getName();
    }

    public String updateMobileNo(Student newStudent){

        //first fetch the original Student
        Student originalStudent = studentRepository.findById(newStudent.getId()).get();

        //keep the other properties as it is
        //only change the required attributes
        originalStudent.setMobileNo(newStudent.getMobileNo());

        studentRepository.save(originalStudent);
        return "Mobile No is updated";
    }
}
